# test:
#   image: espressif/idf:latest
#   script:
#     - touch test.txt
#     #- scp /main/cuby.c firmware@192.168.2.16:/srv/nginx/firmware/
#   artifacts:
#     paths:
#     - test.txt
#     expire_in: 1 week

# build:
#   script:
#     - git submodule update --init --recursive
#     - idf.py build
#   after_script:
    # - execute this after my script  
before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

deploy:
  script:
    - touch test.txt
    # - ip a 
    # - ping -c 4 192.168.2.16  
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null test.txt firmware@192.168.2.16:/srv/nginx/firmware/
  tags:
    - shell