image: espressif/idf:latest

test:
  script:
    - echo "the project directory is - $CI_PROJECT_DIR"
    - cat $CI_PROJECT_DIR/README.md ; echo
    - echo "and where am I? - $PWD"
    - idf.py ; echo

build:
  script:
    - git submodule update --init --recursive
    - idf.py build