# test:
#   image: espressif/idf:latest
#   script:
#     - touch test.txt
#     #- scp /main/cuby.c firmware@192.168.2.16:/srv/nginx/firmware/
#   artifacts:
#     paths:
#     - test.txt
#     expire_in: 1 week

# build:
#   script:
#     - git submodule update --init --recursive
#     - idf.py build
#   after_script:
    # - execute this after my script 

deploy:
  script:
    - touch test.txt
    - ip a 
    - scp test.txt firmware@192.168.2.16:/srv/nginx/firmware/